### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by schmittlema** [swati-test-github09/TestProjet#30]
bs

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit:

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30

**Comment by codeFairOfficial** [comment]
To add a tip for maintainers for this issue, please visit: http://localhost:3000/payments/pay/swati-test-github09/TestProjet/30
